### PR TITLE
Time off display

### PR DESCRIPTION
**Pull request by MehdiElrafi**

### CODE REVIEW

**Comment by MehdiElrafi** [comment]
Display time off

**Comment by mohamedrez** [comment]
@MehdiElrafi if there is 0 days from last year you don't need to mention it just hide it

**Comment by MehdiElrafi** [comment]
**If no remaining days from last year:**
time off

**If it's still some days from last year:**
time off 2

**Comment by MehdiElrafi** [comment]
[Display time off balance](https://trello.com/c/ze4X4P6y/180-display-time-off-balance)

**Pull request merged**
