### PR TITLE
display request type under user name

### PR DESCRIPTION
**Pull request by MehdiElrafi**

### CODE REVIEW

**Comment by MehdiElrafi** [comment]
Screenshot_2023-07-05_17-18-24

**Review by mohamedrez — CHANGES_REQUESTED** [review]
I think the code  could be simpler
Fetch all time requests that are validated,
Fetch all Holidays,
Combine the results in a single array that :
id:,  start:, end:, title: 
now if the event is time request you show : full_name + (Holiday)

**Comment by MehdiElrafi** [comment]
Screenshot_2023-07-06_15-38-35

**Comment by MehdiElrafi** [comment]
Screenshot_2023-07-10_18-06-00

**Review by mohamedrez — APPROVED** [review]

**Review by mohamedrez — APPROVED** [review]

**Pull request merged**
