### PR TITLE
Announcement show page

### PR DESCRIPTION
**Pull request by MehdiElrafi**

### CODE REVIEW

**Comment by MehdiElrafi** [comment]
announcement show page

**Review by mohamedrez — CHANGES_REQUESTED** [review]
show page should not have a form et should not be displayed in the right side but it should redirect the user to the annoucement page

**Comment by MehdiElrafi** [comment]
@mohamedrez This is not a form it's just a style when I display the announcement's info I will work to change it

**Comment by MehdiElrafi** [comment]
table

**Comment by mohamedrez** [comment]
Sorry for the confusion but it needs to look more like a blog post

**Comment by MehdiElrafi** [comment]
announcement show page

**Comment by mohamedrez** [comment]
Can you remove publised from the detail page

**Pull request merged**
